export default {
  getModel: () => ({
    data: [
      {
        row_id: 1,
        is_editable: true,
        is_visible: true,
        row_background_color: "#f2f4f7",
        row_text_color: "#000000",
        span_row: null,
        span_from: null,
        row_order_id: 1,
				row_height: 100,
        column1: "Показатель 1",
        column2: "Категория А",
        column3: "100",
        column4: "2025-01-15",
        column5: "Да",
				column6: "",
        column7: "",
        column8: "",
        column9: "",
        column10: "",
				column11: "",
        column12: "",
        column13: "",
      },
      {
        row_id: 2,
        is_editable: true,
        is_visible: true,
        row_background_color: null,
        row_text_color: null,
        span_row: null,
        span_from: null,
        row_order_id: 2,
				row_height: null,
        column1: "Общий раздел",
        column2: "",
        column3: "130",
        column4: "2025-02-20",
        column5: "Нет",
				column6: "",
        column7: "",
        column8: "",
        column9: "",
        column10: "",
				column11: "",
        column12: "",
        column13: "",
      },
      {
        row_id: 3,
        is_editable: true,
        is_visible: true,
        row_background_color: "#fff3cd",
        row_text_color: "#856404",
        span_row: null,
        span_from: null,
        row_order_id: 3,
				row_height: null,
        column1: "Показатель 3",
        column2: "Категория В",
        column3: "150",
        column4: "2025-03-10",
        column5: "Да",
				column6: "",
        column7: "",
        column8: "",
        column9: "",
        column10: "",
				column11: "",
        column12: "",
        column13: "",
      },
      {
        row_id: 4,
        is_editable: true,
        is_visible: true,
        row_background_color: null,
        row_text_color: null,
        span_row: null,
        span_from: null,
        row_order_id: 4,
				row_height: null,
        column1: "Показатель 4",
        column2: "Категория Г",
        column3: "300",
        column4: "2025-04-05",
        column5: "Нет",
				column6: "",
        column7: "",
        column8: "",
        column9: "",
        column10: "",
				column11: "",
        column12: "",
        column13: "",
      },
      {
        row_id: 5,
        is_editable: true,
        is_visible: true,
        row_background_color: null,
        row_text_color: null,
        span_row: null,
        span_from: null,
        row_order_id: 5,
				row_height: 52,
        column1: "Показатель 5",
        column2: "Категория Д",
        column3: "250",
        column4: "2025-05-12",
        column5: "Да",
				column6: "",
        column7: "",
        column8: "",
        column9: "",
        column10: "",
				column11: "",
        column12: "",
        column13: "",
      },
      {
        row_id: 6,
        is_editable: true,
        is_visible: true,
        row_background_color: null,
        row_text_color: null,
        span_row: null,
        span_from: null,
        row_order_id: 6,
				row_height: null,
        column1: "Показатель 6",
        column2: "Категория Е",
        column3: "175",
        column4: "2025-06-18",
        column5: "Нет",
				column6: "",
        column7: "",
        column8: "",
        column9: "",
        column10: "",
				column11: "",
        column12: "",
        column13: "",
      },
      {
        row_id: 7,
        is_editable: true,
        is_visible: true,
        row_background_color: null,
        row_text_color: null,
        span_row: null,
        span_from: null,
        row_order_id: 7,
				row_height: null,
        column1: "Итого",
        column2: "",
        column3: "",
        column4: "",
        column5: "",
				column6: "",
        column7: "",
        column8: "",
        column9: "",
        column10: "",
				column11: "",
        column12: "",
        column13: "",
      },
			 {
        row_id: 8,
        is_editable: true,
        is_visible: true,
        row_background_color: "#aec6eb",
        row_text_color: null,
        span_row: null,
        span_from: null,
        row_order_id: 8,
				 row_height: null,
        column1: "123",
        column2: "345",
        column3: "24234",
        column4: "098",
        column5: "",
				column6: "",
        column7: "",
        column8: "",
        column9: "",
        column10: "",
				column11: "",
        column12: "",
        column13: "",
      },
    ],
    columnMetadata: [
			{
        column_order: 1,
        column_print_name: "Наименование района",
        column_group: null,
        column_data_type: "text",
        column_regexp: ".*",
        column_is_editable: true,
        column_is_frozen: false,
        column_is_visible: true,
        error_msg: "Введите название показателя",
        max_length: 50,
        metadata_description: "Текстовое поле",
        column_background_color: null,
        column_text_color: null,
        column_text_align: null,
        column_width: null,
      },
			{
        column_order: 2,
        column_print_name: "Наименование образовательной организации",
        column_group: null,
        column_data_type: "dropdown_swim_pool",
        column_regexp: ".*",
        column_is_editable: true,
        column_is_frozen: false,
        column_is_visible: true,
        error_msg: "Выберите категорию",
        max_length: 20,
        metadata_description: '[{"value": "Категория А", "label": "Категория А"}, {"value": "Категория Б", "label": "Категория Б"}, {"value": "Категория В", "label": "Категория В"}, {"value": "Категория Г", "label": "Категория Г"}, {"value": "Категория Д", "label": "Категория Д"}, {"value": "Категория Е", "label": "Категория Е"}]',
        column_background_color: null,
        column_text_color: null,
        column_text_align: null,
        column_width: null,
      },
			{
        column_order: 3,
        column_print_name: "Юридический адрес",
        column_group: null,
        column_data_type: "text",
        column_regexp: ".*",
        column_is_editable: true,
        column_is_frozen: false,
        column_is_visible: true,
        error_msg: "Введите название показателя",
        max_length: 50,
        metadata_description: "Текстовое поле",
        column_background_color: null,
        column_text_color: null,
        column_text_align: null,
        column_width: null,
      },
			{
        column_order: 4,
        column_print_name: "Общее количество спортивных залов",
        column_group: null,
        column_data_type: "datepicker",
        column_regexp: ".*",
        column_is_editable: true,
        column_is_frozen: false,
        column_is_visible: true,
        error_msg: "Выберите дату",
        max_length: 10,
        metadata_description: "Выбор даты",
        column_background_color: null,
        column_text_color: null,
        column_text_align: null,
        column_width: null,
      },
			{
        column_order: 5,
        column_print_name: "Сведения о необходимости проведения ремонтных работ",
        column_group: null,
        column_data_type: "text",
        column_regexp: ".*",
        column_is_editable: true,
        column_is_frozen: false,
        column_is_visible: true,
        error_msg: "Введите название показателя",
        max_length: 50,
        metadata_description: "Текстовое поле",
        column_background_color: null,
        column_text_color: null,
        column_text_align: null,
        column_width: 300,
      },
			{
        column_order: 6,
        column_print_name: "Наличие предписаний надзорно-контрольных органов о необходимости проведения ремонтных работ спортивного зала (да/нет)",
        column_group: null,
        column_data_type: "text",
        column_regexp: ".*",
        column_is_editable: true,
        column_is_frozen: false,
        column_is_visible: true,
        error_msg: "Введите название показателя",
        max_length: 50,
        metadata_description: "Текстовое поле",
        column_background_color: null,
        column_text_color: null,
        column_text_align: null,
        column_width: null,
      },
			{
        column_order: 7,
        column_print_name: "Адрес объекта, в котором расположен  спортивный зал, требующий ремонта",
        column_group: null,
        column_data_type: "text",
        column_regexp: ".*",
        column_is_editable: true,
        column_is_frozen: false,
        column_is_visible: true,
        error_msg: "Введите название показателя",
        max_length: 50,
        metadata_description: "Текстовое поле",
        column_background_color: null,
        column_text_color: null,
        column_text_align: null,
        column_width: null,
      },
			{
        column_order: 8,
        column_print_name: "Планируемый год реализации (с учетом необходиомсти разработки ПСД, проведение экспертизы)",
        column_group: null,
        column_data_type: "text",
        column_regexp: ".*",
        column_is_editable: true,
        column_is_frozen: false,
        column_is_visible: true,
        error_msg: "Введите название показателя",
        max_length: 50,
        metadata_description: "Текстовое поле",
        column_background_color: null,
        column_text_color: null,
        column_text_align: null,
        column_width: null,
      },
      {
        column_order: 9,
        column_print_name: "2025",
        column_group: ["Дополнительная потребность в финансовых затратах на ремонт спортивного зала( в тыс. руб.)", "Текущий ремонт"],
        column_data_type: "int_plus",
        column_regexp: "^\\d+$",
        column_is_editable: true,
        column_is_frozen: false,
        column_is_visible: true,
        error_msg: "Введите целое число",
        max_length: 6,
        metadata_description: "Целое положительное число",
        column_background_color: null,
        column_text_color: null,
        column_text_align: null,
        column_width: null,
      },
      {
        column_order: 10,
        column_print_name: "2026",
        column_group: ["Дополнительная потребность в финансовых затратах на ремонт спортивного зала( в тыс. руб.)", "Текущий ремонт"],
        column_data_type: "int_plus",
        column_regexp: "^\\d+$",
        column_is_editable: true,
        column_is_frozen: false,
        column_is_visible: true,
        error_msg: "Введите целое число",
        max_length: 6,
        metadata_description: "Целое положительное число",
        column_background_color: null,
        column_text_color: null,
        column_text_align: null,
        column_width: 200,
      },
      {
        column_order: 11,
        column_print_name: "2025",
        column_group: ["Дополнительная потребность в финансовых затратах на ремонт спортивного зала( в тыс. руб.)", "Капитальный ремонт"],
        column_data_type: "int_plus",
        column_regexp: "^\\d+$",
        column_is_editable: true,
        column_is_frozen: false,
        column_is_visible: true,
        error_msg: "Введите целое число",
        max_length: 6,
        metadata_description: "Целое положительное число",
        column_background_color: null,
        column_text_color: null,
        column_text_align: null,
        column_width: null,
      },
      {
        column_order: 12,
        column_print_name: "2026",
        column_group: ["Дополнительная потребность в финансовых затратах на ремонт спортивного зала( в тыс. руб.)", "Капитальный ремонт"],
        column_data_type: "int_plus",
        column_regexp: "^\\d+$",
        column_is_editable: true,
        column_is_frozen: false,
        column_is_visible: true,
        error_msg: "Введите целое число",
        max_length: 6,
        metadata_description: "Целое положительное число",
        column_background_color: null,
        column_text_color: null,
        column_text_align: "CENTER",
        column_width: null,
      },
      {
        column_order: 13,
        column_print_name: "Текущий ремонт",
        column_group: ["Фактические затраты"],
        column_data_type: "dropdown_swim_pool",
        column_regexp: ".*",
        column_is_editable: true,
        column_is_frozen: false,
        column_is_visible: true,
        error_msg: "Выберите Да/Нет",
        max_length: 3,
        metadata_description: '[{"value": "Дададададададаlflflflf", "label": "Дададададададаlflflflf"}, {"value": "НетНетнетнетнетytnytnytn", "label": "НетНетнетнетнетytnytnytn"}]',
        column_background_color: null,
        column_text_color: null,
        column_text_align: null,
        column_width: null,
      },
			// {
        // column_order: 14,
        // column_print_name: "Наименование района",
        // column_group: null,
        // column_data_type: "text",
        // column_regexp: ".*",
        // column_is_editable: true,
        // column_is_frozen: false,
        // column_is_visible: true,
        // error_msg: "Введите название показателя",
        // max_length: 50,
        // metadata_description: "Текстовое поле",
        // column_background_color: null,
        // column_text_color: null,
        // column_text_align: null,
        // column_width: null,
      // },
    ],
    tabMetadata: {
      id: 105,
      system_name: "mock_table_7x5",
      print_name: "Тестовая таблица 7x5",
      report_id_fk: 103,
      description: "Мок для разработки",
      can_add_row: true,
      is_visible: true,
      tab_number: 1,
    },
    canAddRow: true,
    tableStyle: {
      textColor: "black",
      backgroundColor: "white",
    },
    userPermissions: "report_edit",
    selectedRowsIds: [],
    cellOverrides: {
      "6-2": {  // предпоследняя строка, третья колонка
        column_is_editable: false,
				column_data_type: "sum_column_mock",
				metadata_description: "0-5",
				column_regexp: ".*",
        column_background_color: "#e2e3e5",
        font_weight: "bold",
      },
			 "7-4": {  // последняя строка, пятая колонка
        column_is_editable: false,
				column_data_type: "sum_row_mock",
				metadata_description: "0, 1, 2, 3",
				column_regexp: ".*",
        column_background_color: "#e2e3e5",
        font_weight: "bold",
      },
			"7-1": {  // последняя строка, вторая колонка
        column_is_editable: true,
				column_data_type: "int_plus",
				metadata_description: "",
				column_regexp: ".*",
      },
			"7-3": {  // последняя строка, вторая колонка
        column_is_editable: true,
				column_data_type: "int_plus",
				metadata_description: "",
				column_regexp: ".*",
      },
    },
    span_mass: [
      { "type": "row", "order": 1, "interval_start": 0, "interval_end": 1 },
      { "type": "column", "order": 1, "interval_start": 3, "interval_end": 5 }
    ],
  }),
};